services:
  postgres:
    image: postgres
    restart: unless-stopped
    command: -c shared_preload_libraries=pg_stat_statements
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024m
  api:
    build:
      context: ./projects/api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - 8080:80
    depends_on:
      - postgres
    healthcheck:
      test: curl -f http://localhost:80/docs
      interval: 5s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024m
  agent:
    image: vision-ai-agent:compose
    restart: unless-stopped
    env_file: .env
    ports:
      - 6060:6060
    depends_on:
      api:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048m
  stream-server:
    image: bluenviron/mediamtx:latest
    restart: unless-stopped
    ports:
      - 8888:8888
      - 8554:8554
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024m
  send-stream:
    build:
      context: ./scripts
      dockerfile: stream.Dockerfile
    restart: unless-stopped
    environment:
      DATA_PATH: /data
      STREAM_SERVER: stream-server
    volumes:
      - stream-data:/data
    depends_on:
      - stream-server
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 3072m
volumes:
  postgres-data:
  stream-data:
