services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    image: ghcr.io/prefeitura-rio/vision-ai-api:latest
    restart: always
    env_file: .env
    ports:
      - 8080:80
    depends_on:
      - postgres
volumes:
  postgres-data:
