name: Frontend

on:
  push:
    paths:
      - ".github/workflows/frontend*"
      - "projects/frontend/**/*"

jobs:
  deploy:
    name: Build and Deploy
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      DOCKERHUB_REPOSITORY: vision-ai-frontend
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: prefeiturario
      GCP_PROJECT_ID: ${{ github.ref == 'refs/heads/main' && secrets.PRODUCTION_GCP_PROJECT_ID || secrets.STAGING_GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ github.ref == 'refs/heads/main' && secrets.PRODUCTION_GCP_SA_KEY || secrets.STAGING_GCP_SA_KEY }}
      GCR_SERVICE: vision-ai
      GCR_REGION: us-central1

    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'Front-end (Production)' || 'Front-end (Staging)' }}
      url: ${{ github.ref == 'refs/heads/main' && 'https://fe.vision-ai.dados.rio/' || 'https://staging-fe.vision-ai.dados.rio/' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Auth
        id: docker-auth
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Write .env file containing the API URL (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "NEXT_PUBLIC_API_URL=https://api.vision-ai.dados.rio" > ./projects/frontend/.env

      - name: Write .env file containing the API URL (Staging)
        if: github.ref == 'refs/heads/development'
        run: |
          echo "NEXT_PUBLIC_API_URL=https://staging-api.vision-ai.dados.rio" > ./projects/frontend/.env

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./projects/frontend
          file: ./projects/frontend/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:${{ github.sha }}
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GCP_SA_KEY }}'

      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.GCR_SERVICE }}-frontend
          region: ${{ env.GCR_REGION }}
          image: docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:${{ github.sha }}
          flags: '--port=3000 --allow-unauthenticated --concurrency=100 --verbosity=debug --session-affinity'
