name: Identifier

on:
  push:
    paths:
      - ".github/workflows/identifier*"
      - "projects/identifier/**/*"
      - "libs/base/**/*"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.x"

      - name: Set up dependencies
        run: |
          cd projects/identifier/
          pip install -U pip
          pip install -r requirements-dev.txt

      - name: Run linter
        run: |
          cd projects/identifier/
          black . && isort . && flake8 .

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
    needs: [lint]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      GCP_PROJECT_ID: ${{ github.ref == 'refs/heads/main' && secrets.PRODUCTION_GCP_PROJECT_ID || secrets.STAGING_GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ github.ref == 'refs/heads/main' && secrets.PRODUCTION_GCP_SA_KEY || secrets.STAGING_GCP_SA_KEY }}
      GCF_NAME: vision-ai-function
      GCF_RUNTIME: python311
      GCF_ENTRY_POINT: predict
      GCF_MEMORY_MB: 1024
      GCF_REGION: us-central1
      GCF_TIMEOUT: 60
      GCF_MIN_INSTANCES: 50
      GCF_MAX_INSTANCES: 200
      GCF_TOPIC: vision-ai

    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'Identifier (Production)' || 'Identifier (Staging)' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove soft link and copy libs to API directory
        run: |
          rm projects/identifier/libs
          mkdir -p projects/identifier/libs
          cp -r libs/* projects/identifier/libs/

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: Deploy to Google Cloud Functions
        run: |
          gcloud functions deploy ${{ env.GCF_NAME }} \
            --project=${{ env.GCP_PROJECT_ID }} \
            --gen2 \
            --runtime=${{ env.GCF_RUNTIME }} \
            --region=${{ env.GCF_REGION }} \
            --source=projects/identifier/ \
            --entry-point=${{ env.GCF_ENTRY_POINT }} \
            --memory=${{ env.GCF_MEMORY_MB }}MB \
            --timeout=${{ env.GCF_TIMEOUT }}s \
            --trigger-topic=${{ env.GCF_TOPIC }} \
            --min-instances=${{ env.GCF_MIN_INSTANCES }} \
            --max-instances=${{ env.GCF_MAX_INSTANCES }} \
            --set-secrets=GEMINI_API_KEY=gemini-api-key-cloud-functions:latest,VISION_AI_API_SECRETS=vision-ai-api-secrets-cloud-functions:latest
            --set-env-vars=GCP_PROJECT_ID=${{ env.GCP_PROJECT_ID }}
